name: Deploy SQL Scripts to SQL Server

# Triggers the workflow on push to main or development branches
on:
  push:
    branches:
      - main
      - development

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository to get the SQL scripts
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Install the SQL Server tools like sqlcmd
      - name: Install SQL Server module and tools
        run: |
          Install-Module -Name SqlServer -Force -SkipPublisherCheck
          Import-Module SqlServer
          
      -name: Create Database if not exists
       run: |
         sqlcmd -S ${{ secrets.SQL_SERVER }} -U ${{ secrets.SQL_USER }} -P ${{ secrets.SQL_PASSWORD }} -Q "IF NOT EXISTS(SELECT * FROM sys.databases WHERE name = 'Senior-Year-Students') BEGIN CREATE DATABASE Senior-Year-Students END"

      # Step 3: Run the CreateTables.sql script
      - name: Run CreateTables.sql script
        run: |
          sqlcmd -S ${{ secrets.SQL_SERVER }} -U ${{ secrets.SQL_USER }} -P ${{ secrets.SQL_PASSWORD }} -i ./scripts/Students_Table.sql
      # Step 5: Run the Subject.sql script
      - name: Run Subject.sql script
        run: |
          sqlcmd -S ${{ secrets.SQL_SERVER }} -U ${{ secrets.SQL_USER }} -P ${{ secrets.SQL_PASSWORD }} -i ./scripts/Subject.sql