name: Deploy SQL Scripts to SQL Server

on:
  push:
    branches:
      - main
      - development

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository to get the SQL scripts
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Install the SQL Server tools like sqlcmd with AllowClobber to avoid conflicts
      - name: Install SQL Server module and tools
        run: |
          Install-Module -Name SqlServer -Force -AllowClobber
          Import-Module SqlServer

      # Step 3: Create Database if not exists
      - name: Create Database if not exists
        run: |
          sqlcmd -S ${{ secrets.SQL_SERVER }} -U ${{ secrets.SQL_USER }} -P ${{ secrets.SQL_PASSWORD }} -Q "IF NOT EXISTS(SELECT * FROM sys.databases WHERE name = 'Senior-Year-Students') BEGIN CREATE DATABASE [Senior-Year-Students] END"

      # Step 4: Run the CreateTables.sql script
      - name: Run CreateTables.sql script
        run: |
          sqlcmd -S ${{ secrets.SQL_SERVER }} -U ${{ secrets.SQL_USER }} -P ${{ secrets.SQL_PASSWORD }} -d Senior-Year-Students -i ./scripts/Students_Table.sql

      # Step 5: Run the Subject.sql script
     ​⬤